name: "Docker Django Operations"
description: "Run Django collectstatic and migrations in temporary Docker containers"
inputs:
  host:
    description: "The host IP or domain"
    required: true
  project_folder:
    description: "The project folder name"
    required: true
  ssh_script:
    description: "Path to SSH script"
    required: true
  operations:
    description: "Comma-separated list of operations: collectstatic,migrate"
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify SSH Script
      shell: bash
      run: |
        # Check if SSH script exists
        if [ ! -f "$SSH_SCRIPT" ]; then
          echo "Error: SSH script not found at $SSH_SCRIPT"
          echo "This action expects the SSH script to be created by the calling workflow"
          exit 1
        fi
        echo "SSH script found at $SSH_SCRIPT"
      env:
        SSH_SCRIPT: ${{ inputs.ssh_script }}

    - name: Discover Docker Configuration
      id: docker-config
      shell: bash
      run: |
        set -euo pipefail

        echo "Discovering Docker configuration..."

        # Get the running container info (look for Django/web container)
        CONTAINER_INFO=$($SSH_SCRIPT "docker ps --filter 'name=server' --format '{{.Image}} {{.Names}} {{.Networks}}' | head -1")

        if [ -z "$CONTAINER_INFO" ]; then
          # Try alternative container names
          CONTAINER_INFO=$($SSH_SCRIPT "docker ps --filter 'name=web' --format '{{.Image}} {{.Names}} {{.Networks}}' | head -1")
        fi

        if [ -z "$CONTAINER_INFO" ]; then
          # Try without filter, get first running container
          CONTAINER_INFO=$($SSH_SCRIPT "docker ps --format '{{.Image}} {{.Names}} {{.Networks}}' | head -1")
        fi

        if [ -z "$CONTAINER_INFO" ]; then
          echo "No running containers found"
          exit 1
        fi

        echo "Found container: $CONTAINER_INFO"
        echo "container_info=$CONTAINER_INFO" >> "$GITHUB_OUTPUT"

        # Extract image, name, and network
        IMAGE=$(echo $CONTAINER_INFO | awk '{print $1}')
        NAME=$(echo $CONTAINER_INFO | awk '{print $2}')
        NETWORK=$(echo $CONTAINER_INFO | awk '{print $3}')

        echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
        echo "name=$NAME" >> "$GITHUB_OUTPUT"
        echo "network=$NETWORK" >> "$GITHUB_OUTPUT"

        # Get volume mounts from the container
        VOLUMES=$($SSH_SCRIPT "docker inspect $NAME --format '{{range .Mounts}} -v {{.Source}}:{{.Destination}}{{if not .RW}}:ro{{end}}{{end}}'")
        echo "volumes=$VOLUMES" >> "$GITHUB_OUTPUT"

        # Get environment file path
        ENV_FILE="/home/ubuntu/$PROJECT_FOLDER/.env"
        echo "env_file=$ENV_FILE" >> "$GITHUB_OUTPUT"
      env:
        HOST: ${{ inputs.host }}
        PROJECT_FOLDER: ${{ inputs.project_folder }}
        SSH_SCRIPT: ${{ inputs.ssh_script }}

    - name: Run Collect Static
      if: contains(inputs.operations, 'collectstatic')
      shell: bash
      run: |
        set -euo pipefail

        echo "Running collectstatic in temporary Docker container..."

        # Build the docker run command with proper volume mounts
        CMD="docker run --rm \
          --user root \
          --network ${{ steps.docker-config.outputs.network }} \
          -v ${{ steps.docker-config.outputs.env_file }}:/app/.env:ro"

        # Add volumes if any
        if [ -n "${{ steps.docker-config.outputs.volumes }}" ]; then
          CMD="$CMD ${{ steps.docker-config.outputs.volumes }}"
        fi

        # Add the image and command
        CMD="$CMD ${{ steps.docker-config.outputs.image }} python manage.py collectstatic --no-input"

        echo "Executing: $CMD"
        $SSH_SCRIPT "$CMD"
      env:
        SSH_SCRIPT: ${{ inputs.ssh_script }}

    - name: Run Migrations
      if: contains(inputs.operations, 'migrate')
      shell: bash
      run: |
        set -euo pipefail

        echo "Running migrations in temporary Docker container..."

        # Build the docker run command with proper volume mounts
        CMD="docker run --rm \
          --network ${{ steps.docker-config.outputs.network }} \
          -v ${{ steps.docker-config.outputs.env_file }}:/app/.env:ro"

        # Add volumes if any
        if [ -n "${{ steps.docker-config.outputs.volumes }}" ]; then
          CMD="$CMD ${{ steps.docker-config.outputs.volumes }}"
        fi

        # Add the image and command
        CMD="$CMD ${{ steps.docker-config.outputs.image }} python manage.py migrate"

        echo "Executing: $CMD"
        $SSH_SCRIPT "$CMD"
      env:
        SSH_SCRIPT: ${{ inputs.ssh_script }}
