name: "Ship Export"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [staging, prod]
    steps:
      - name: Install OSH
        run: curl -sS https://rohittp.com/scripts/utils/installer.sh | bash -s osh

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}

      - uses: rohittp0/wiregaurd@v2
        with:
          config: ${{ secrets.WG_CONFIG_BASE64 }}

      # Import secrets from Infisical
      - name: Import env secrets from Infisical
        uses: Infisical/secrets-action@v1.0.9
        with:
          # Auth method: universal (client credentials)
          method: universal
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          # Project / environment
          project-slug: marine
          env-slug: ${{ matrix.environment }}
          # Self-hosted domain
          domain: ${{ secrets.INFISICAL_DOMAIN }}
          # Export to a .env file in the workspace
          export-type: file
          file-output-path: /.env

      - name: Extract Env
        id: extract
        run: |
          source .env
          IP=$(osh "ubuntu@${HOST}" --ip)
          echo "host=$HOST" >> "$GITHUB_OUTPUT"
          echo "ip=$IP" >> "$GITHUB_OUTPUT"
          echo "slack_webhook=$SLACK_WEBHOOK_URL" >> "$GITHUB_OUTPUT"
          echo "timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> "$GITHUB_OUTPUT"

      - name: Add SSH key to known hosts
        run: ssh-keyscan -H "${{ steps.extract.outputs.ip }}" >> ~/.ssh/known_hosts

      - name: Create SSH Script
        run: |
          echo "ssh -i ~/.ssh/private.key \"ubuntu@$HOST\" \$@" > s.sh
          chmod +x s.sh
        env:
          HOST: ${{ steps.extract.outputs.ip }}

      - name: Export
        run: ./s.sh "shell server run python manage.py export_data --type ships --batch-size 1000"

      - name: Notify Slack on failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": { "type": "plain_text", "text": "🚨 Ship Export Failed", "emoji": true }
                },
                {
                  "type": "section",
                  "fields": [
                    { "type": "mrkdwn", "text": "*Env:*\n${{ matrix.environment }}" },
                    { "type": "mrkdwn", "text": "*Time:*\n${{ steps.extract.outputs.timestamp }}" }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ steps.extract.outputs.slack_webhook }}
