name: Vercel Deploy Commit

on:
  repository_dispatch:
    types: [vercel-commit]

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: vercel-commit-${{ github.event.client_payload.repo }}-${{ github.event.client_payload.branch }}
  cancel-in-progress: true

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      # Checkout the target repo at the requested branch using a PAT
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.branch }}
          # PAT must have repo (or at least contents:write) on the target repo
          token: ${{ secrets.VERCEL_PAT }}
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name  "central-bot"
          git config user.email "central-bot@users.noreply.github.com"

      - name: Create empty commit
        id: commit
        shell: bash
        run: |
          set -euo pipefail
          git commit --allow-empty -m "chore: vercel deploy"
          git push origin HEAD:refs/heads/${{ github.event.client_payload.branch }}
